### ISSUE TITLE
Bring out the big guns

### ISSUE THREAD

**Issue by qtdyn** [SilverAndro/shiv#1]
Since this is a silly project, have a silly feature request :3

Instead of using ByteBuddy & a Java Agent, why not use a native library to get the JVMTI context to make transformations? It would remove the need for a JDK runtime and remove a library.

I maintain my own [native transformation library](https://github.com/stardust-enterprises/deface), but it's written in Kotlin, so I don't think it'd be appropriate for this project.

**Comment by SilverAndro** [comment]
id use kotlin but with how early i am in the launch process, + the classloader issues itd just be another thing to keep track of when kotlin is on the classpath or not 😅

main reason im using byte buddy is because i actually know how java agents and stuff work, as well as minecraft shipping a jdk by default (so i can blame jre users directly)

im sure learning all that would be *interesting*, but i also do want to be able to have some sense of maintainability since i have other projects as well lmao, and theres 0 chance id get it right any time soon

**Comment by qtdyn** [comment]
> minecraft shipping a jdk by default

***what***

well then I understand it'd be more of a maintaining hassle than anything, oh well :^)

**Comment by SilverAndro** [comment]
> ***what***

Yeah i dunno! i double checked myself but it seems to be the case. Maybe something about the profiler commands and such?

Thanks for the suggestion though 💖
